### PR TITLE
feat: Support for @types/google.maps

### LINKED ISSUE #690: Support for @types/google.maps
Hi,
I would like to upgrade my project to use `@types/google.maps`, but `@googlemaps/markermanager` and `@googlemaps/ogc` doesn't support this package. I see `@googlemaps/markerclustererplus` supports it already. 
Is there any chance to upgrade types dependency? I could try to prepare PR, if you want. 😄

### PR DESCRIPTION
**Pull request by piotter121**
Fixes #690 🦕

### CODE REVIEW

**Comment by piotter121** [comment]
@googlebot I signed it!

**Comment by jpoehnelt** [comment]
@piotter121 Are you primarily interested in the jest mocks?

**Comment by piotter121** [comment]
No, but I am going to.

**Comment by piotter121** [comment]
When can we expect to get this changes in new versions of NPM packages?

**Comment by jpoehnelt** [comment]
https://www.npmjs.com/package/@googlemaps/jest-mocks has been published.

**Comment by jpoehnelt** [comment]
@piotter121 I split jest-mocks into a separate repo, https://github.com/googlemaps/js-jest-mocks

**Comment by piotter121** [comment]
Good to see `@googlemaps/jest-mocks` published, but primarily I was interested in `@googlemaps/ogc` and `@googlemaps/markermanager` as I wrote in #690.

**Comment by jpoehnelt** [comment]
got it. will publish those and split to separate repo too

**Pull request merged**
