### PR TITLE
Hiding boxes for clustered markers

### PR DESCRIPTION
**Pull request by tymarats**
This makes InfoBox work better with MarkerClusterer, hiding and showing boxes together with markers.

### CODE REVIEW

**Comment by tymarats** [comment]
I signed it.

**Comment by tymarats** [comment]
I signed it.

**Comment by tymarats** [comment]
This should fix https://github.com/googlemaps/v3-utility-library/issues/358

**Comment by stephenmcd** [comment]
Thanks a lot!

**Pull request merged**
