### PR TITLE
fix: missing `getClickableIcons` in class `_Map` [@googlemaps/jest-mocks]

### LINKED ISSUE #680: @googlemaps/jest-mocks - `getClickableIcons` method missing in class `Map_`
#### Environment details

1. version: googlemaps/jest-mocks@0.1.0
2. typescript version: 3.9.3

#### Steps to reproduce

After installing and compiling, there's a type error:

```
Class 'Map_' incorrectly implements class 'Map<Element>'. Did you mean to extend 'Map<Element>' and inherit its members as a subclass?
  Property 'getClickableIcons' is missing in type 'Map_' but required in type 'Map<Element>'.
```

### PR DESCRIPTION
**Pull request by Xdudu**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #680

### CODE REVIEW

**Comment by Xdudu** [comment]
@googlebot I signed it!

**Comment by Xdudu** [comment]
Any schedule for a new release with this fix? Thanks

**Comment by jpoehnelt** [comment]
Just published. Sorry about that, there is no continuous deployment for this repo.

**Comment by jpoehnelt** [comment]
https://www.npmjs.com/package/@googlemaps/jest-mocks/v/0.1.1

**Pull request merged**
