### PR TITLE
Update maplabel.js

### PR DESCRIPTION
**Pull request by marlonnardi**
Z-index correction.

### CODE REVIEW

**Comment by marlonnardi** [comment]
I signed it!

**Comment by amuramoto** [comment]
@marlonnardi Can you provide a bit more detail on the issue this PR is fixing?

**Comment by marlonnardi** [comment]
the maplabel presents a problem for display in some cases, such as when working with Polygon and GeoJSON.

Example, without fix:
https://plnkr.co/edit/KvhIoRoibsbKk9e4k1Ch?p=preview

with fix:
https://plnkr.co/edit/6itHWltPyugmZOwXhXsd?p=preview

**Comment by amuramoto** [comment]
Thanks for the PR!

**Pull request merged**
