### PR TITLE
feat(markerclustererplus): rewrite source to typescript

### PR DESCRIPTION
**Pull request by thekip**
https://github.com/googlemaps/v3-utility-library/issues/572

the description will appear soon together with questions and my thoughts

### CODE REVIEW

**Comment by jpoehnelt** [comment]
@thekip should rebase on master for #591

**Comment by thekip** [comment]
@googlebot I signed it!

**Comment by thekip** [comment]
What I've done: 

1. Split source to one class per file
2. Rewrote to typescript with diagnostic level `noImplicitAny: true`
3. Changed old-fashioned `var `- hoisting style of defining variables to const/let
4. Created `OverlayViewSafe` shim as described here https://github.com/googlemaps/v3-utility-library/issues/573#issuecomment-564942397
5. Refactored a bit `ClusterIcon.show` method using es6 string literals
6. Created a new rollup config using `packages/loader` as example.

And now questions and things to discuss: 

1. I didn't test docs. And didn't try to generate or dig into it. I'm not sure that after these changes it's still generating correctly. 
I tried to keep as many docs as possible, including types for returns and function params.
Posible we should consider stick with only TS types and remove jsdoc type annotations as redundant, but i don't know how you docs generating tool works.

2. Building. I didn't dig too much into build pipeline. Just port config from another package. Will appreciate if you take care of that.

3. Constants such as `IMAGE_PATH` or `CALCULATOR`, In this PR I put them as a static field on the`MarkerClusterer` class, but I want to clarify something.

    I dig into git log and found that previously they were defined on a constructor (like a static field), then in one of the recent commits, they were moved inside a constructor and become a class member. 
The question here, how they supposed to use? Looks like previously they were used as 'global defaults' for the whole module. 
But in the current version, it isn't possible to change them before instantiating, and this makes no sense.  Or they used just like a "constants" to hold some value? If so, it's probably better to put them outside of a class using `const` keyword.

4. Possible Breaking changes:
 - I changed type of `ClusterIconStyle.anchorText` and `ClusterIconStyle.anchorIcon` from `number[]` to tuple `[number, number]`, this may affect some users because array of number isn't assignable to tuple. 
- possibly import of the lib was changed. Despite the fact I kept default import of `MarkerClusterer` class. Looks like the expression `import MarkerClusterer from '@google/markerclustererplus'` causes an error in a host project. This is TBA and probably related with a building pipeline.

**Comment by thekip** [comment]
5. Linting. I didn't implement linting. Since default eslint config not  play with TS files. 
Question here, is it OK to just copy all lint configuration from `packages/loader` or we need to create new lint file with appropriate settings for this package? 

I'm asking because I tried already, and have got huuuge amount of lint errors. Seems js-codestyle used for old source was not quite aligned with wat set up for linting fo TS files.

**Comment by thekip** [comment]
Added a few commits, more details in commit messages. 

Today played with docs generating and found that current pipeline generating something completely different from that I used to use (found this old copy in google http://159.203.119.72/node_modules/markerclustererplus/docs/reference.html)

So for sure, TypeDoc can read types from TS annotations,and in the following commits, I will cleanup docs. 

Question: typedoc does not allow to describe events, but there are some in the code, how it's supposed to be exposed to users?

**Comment by thekip** [comment]
Committed docs cleanup and aligning for TypeDoc. I'm not sure still, should we expose to docs all internal classes such as `Cluster` or `ClusterImage` or we should hide them using `@hidden/@ignore` taking into consideration that they are accessible now from exports. 

@jpoehnelt waiting for your answers about building, constants and linting

**Comment by jpoehnelt** [comment]
> 1. I didn't test docs. And didn't try to generate or dig into it. I'm not sure that after these changes it's still generating correctly.
>    I tried to keep as many docs as possible, including types for returns and function params.
>    Posible we should consider stick with only TS types and remove jsdoc type annotations as redundant, but i don't know how you docs generating tool works.

Looks like you have the docs working. `@hidden/@ignore` might be nice but not critical for this pr.

> 2. Building. I didn't dig too much into build pipeline. Just port config from another package. Will appreciate if you take care of that.

I can do that. 
> 3. Constants such as `IMAGE_PATH` or `CALCULATOR`, ... Or they used just like a "constants" to hold some value? If so, it's probably better to put them outside of a class using `const` keyword.

They should probably be constants. The user can override with options.

> 4. Possible Breaking changes:
> 
> * I changed type of `ClusterIconStyle.anchorText` and `ClusterIconStyle.anchorIcon` from `number[]` to tuple `[number, number]`, this may affect some users because array of number isn't assignable to tuple.

Might as well get the full benefit of typescript by using the tuple. 👍 

> * possibly import of the lib was changed. Despite the fact I kept default import of `MarkerClusterer` class. Looks like the expression `import MarkerClusterer from '@google/markerclustererplus'` causes an error in a host project. This is TBA and probably related with a building pipeline.

I can check on the build 
changes.
> Linting
Looks like there are some real errors there and a few style related ones.
```
/home/travis/build/googlemaps/v3-utility-library/packages/markerclustererplus/src/cluster-icon.ts
  9:8  error  Parsing error: Unexpected token interface
/home/travis/build/googlemaps/v3-utility-library/packages/markerclustererplus/src/cluster.ts
  9:11  error  Parsing error: Unexpected token map_
```

Have you gotten this working with one of the examples?

**Comment by thekip** [comment]
Thanks for reply

> Linting

Looks like there are some real errors there and a few style-related ones.

Actually I haven't commit typescript compatible lint file. So errors which travis shows just about that eslint parser could not parse typescript file. 

On my local machine, I copied lint file from `packages/loader` and got that working with a lot of style errors (mostly prettier's).

So if this is a default style which everybody agreed one I just run eslint with `--fix` and then commit.

 
> Have you gotten this working with one of the examples?

I tested it on my real application but since last time I did some new changes, so need to test once again.

**Comment by jpoehnelt** [comment]
>So if this is a default style which everybody agreed one I just run eslint with --fix and then commit.

I'm fine with that.

**Comment by thekip** [comment]
In 3 latest commits: 

1. Implement linitng for `*.ts` files and fix all errors manually + `--fix`
2. Change exports and rollup config accordingly
   -  Don't export non-public things such as `Clusterer` and `ClusterIcon` (all interfaces used for configuration is still exported)
   - Export `MarkerClusterer` as default (removed named export)
   - Changed rollup config accordingly that in UMD `var MarkerClusterer = (default export)`

I checked all examples, they are works. 
Actually i finished in all tasks related to this PR even that what I asked before.

So waiting for review and can be merged.

**Comment by jpoehnelt** [comment]
@thekip thanks for the great work!

**Pull request merged**
