### PR TITLE
Add MarkerWithLabel.dispose() to break a circular reference preventing gc

### PR DESCRIPTION
**Pull request by patros**
I have an app that creates and updates markers dynamically. I noticed a memory leak and narrowed it down to a circular reference between the MarkerWithLabel marker and the label. This commit just adds a dispose call that breaks the circular reference to allow garbage collection.

### CODE REVIEW

**Comment by patros** [comment]
I signed it!

**Comment by stephenmcd** [comment]
Thanks for this! 

Could you possibly setup a minimal example that demonstrates the issue so I can verify the fix?

**Comment by patros** [comment]
Try this...

```
<html>
<body>
<div id="map" style="height: 600px"></div>
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script src="markerwithlabel.js"></script>
<script>
    var map;
    map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: -34.397, lng: 150.644},
        zoom: 8
    });

    var markers = [];
	var markerCount = 2500;

	function clearMarkers() {
        for (var i=0; i<markerCount; i++) {
            if (markers[i].dispose) {
                markers[i].dispose();
            } else {
                markers[i].setMap(null);
                markers[i] = null;
            }
		}
		window.setTimeout(makeMarkers, 2000);
	}
	
	function makeMarkers() {
        for (var i=0; i<markerCount; i++) {
            markers[i] = new MarkerWithLabel({
                position: {lat: -34.397, lng: 150.644},
                icon: {
                    path: google.maps.SymbolPath.CIRCLE,
                    scale: 5,
                    fillColor: "black",
                    fillOpacity: 1
                },
                labelContent: "*",
                labelAnchor: new google.maps.Point(15, 0),
                labelInBackground: false
            });
            markers[i].setMap(map);
        }
		window.setTimeout(clearMarkers, 5000);
    }

    window.setTimeout(makeMarkers, 2000);
</script>
</body>

</html>
```

You'll need to let it run for a few minutes but it should reproduce the problem easily enough. What's interesting is that looking at the memory timeline profile it looks like the garbage collector is doing its job but process memory keeps increasing out of control.

**Comment by patros** [comment]
I only became aware of the issue when testing my app on a Windows machine with IE. Let me check what browser/os combinations it happens on.

**Comment by patros** [comment]
Seems to happen for IE11 on Windows 10. It is also happening with Firefox ESR on Debian Stable. It doesn't seem to be affecting Chrome on Windows or Linux. Or if it is the leak is much slower. If you want me to try any other browser/os combos or want to know more detail about my environments let me know.

**Comment by patros** [comment]
And, you'll probably have to turn down the number of markers it makes in one go so the IE javascript engine can handle it without becoming too unresponsive.

**Comment by patros** [comment]
I need to do more investigation... the example still results in IE memory usage skyrocketing with my "fix" while in my app it doesn't with the "fix"... I'll close this pull request and open a new one when I can reliably reproduce the problem and solution.

**Pull request closed without merging**
