### PR TITLE
Update marker with label: Improve error handling of position

### PR DESCRIPTION
**Pull request by alex-Hudson**
Improve code for when position resolves as undefined

### CODE REVIEW

**Comment by alex-Hudson** [comment]
@googlebot I signed it!

**Comment by jpoehnelt** [comment]
looks like you still need to sign the cla, https://cla.developers.google.com/.

**Comment by alex-Hudson** [comment]
Hi,
My boss is looking at it, apologies. It will probably be done today.
Thanks
Alex

**Comment by alex-Hudson** [comment]
@googlebot I signed it!

**Comment by alex-Hudson** [comment]
Hi,
You should now see that my boss has signed the CLA.
Many thanks
Alex

**Comment by jpoehnelt** [comment]
@alex-Hudson The primary contact for the CLA will need to add you(your email attached to the commit) to the group they used in one of the fields so that the CLA propogates to your Github account.

**Comment by alex-Hudson** [comment]
@jpoehnelt I have now done that. Thanks

**Comment by alex-Hudson** [comment]
@googlebot I signed it!

**Comment by alex-Hudson** [comment]
@googlebot I signed it!

**Comment by jpoehnelt** [comment]
Thanks @alex-Hudson for your patience.

It's available in https://www.npmjs.com/package/@google/markerwithlabel/v/1.2.11.

**Pull request merged**
